apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    author: Ismoil
  name: nginx2
  namespace: exam-27
spec:
  containers:
  - image: nginx
    name: nginx2
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
